// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc166.Robot166.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc166.Robot166.Robot;
import org.usfirst.frc166.Robot166.subsystems.Shoulder;
/**
 *
 */
public class MoveShoulderToLoadPosition extends Command {
    public MoveShoulderToLoadPosition() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shoulder);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.shoulder.moveToInPosition();
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (Robot.shoulder.isShoulderIn());
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.shoulder.stop();
        Robot.shoulder.setCurrentPosition(Shoulder.Position.In);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        Robot.shoulder.stop();
        Robot.shoulder.setCurrentPosition(Shoulder.Position.Unknown);
    }
}
