// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc166.Robot166.subsystems;

import org.usfirst.frc166.Robot166.RobotMap;
import org.usfirst.frc166.Robot166.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

public class Shoulder extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController motor = RobotMap.shoulderMotor;
    AnalogChannel potentiometer = RobotMap.shoulderPotentiometer;
    DigitalInput ballAcquiredLimit = RobotMap.shoulderBallAcquiredLimit;
    DigitalInput outGuardLimit = RobotMap.shoulderOutGuardLimit;
    DigitalInput inGuardLimt = RobotMap.shoulderInGuardLimt;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATION
    public static final double shoulderSpeed = 10;
    public static double potVal;
    public static double homePosHi = 20;//rename to home position
    public static double homePosLo = 10;//rename to home position
    public static boolean isShoulderOut;
    public static boolean isShoulderIn;

    // Put methods for controlling this subsystem
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    public boolean isHomePos() {
        potVal = getPotVal();
        if (potVal >= homePosLo && potVal <= homePosHi) {
            return true;
        }
        else {
            return false;
        }
    }

    public boolean getOutLmt() {//rename to ISSHOULDEROUT
        return RobotMap.shoulderOutGuardLimit.get();
    }

    public boolean getInLmt() {//rename to ISSHOULDERIN
        return RobotMap.shoulderInGuardLimt.get();
    }

    public double getPotVal() {
        return potentiometer.getVoltage();
    }

    public void moveToHome() {
        potVal = getPotVal();
        if (potVal > homePosHi)//if potval is larger than 9
        {
            motor.set(shoulderSpeed * -1);
        }
        if (potVal < homePosLo)//if potval is less than 9
        {
            motor.set(shoulderSpeed);
        }
    }

    public void moveToOut() {
        motor.set(shoulderSpeed);
    }

    public void moveToIn() {
        motor.set(shoulderSpeed * -1);
    }
}
