// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc166.Robot166.subsystems;

import org.usfirst.frc166.Robot166.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Transmission extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid solenoid = RobotMap.transmissionSolenoid;
    Compressor compressor = RobotMap.transmissionCompressor;
    AnalogChannel pressureSensor = RobotMap.transmissionPressureSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    //Initialization function for the transmission. Executed when Instantiated.
    public Transmission() {
        super();                //Allow higher level software to initialize first
        compressor.start();     //Start Kompressor System
        solenoid.set(false);    //Turns off solenoid
    }

    //Function to set transmission to high speed
    public void shiftToHighGear() {
        solenoid.set(false); // Turns off Solenoid
    }

    //Function to set transmission to low speed
    public void shiftToLowGear() {
        solenoid.set(true); // Turns on Solenoid
    }

    //Function to set transmission to high speed
    public boolean isReady() {
        //If pressure sensor is greater than 1.2 volts, which is approximately 44 PSI
        if (pressureSensor.getVoltage() > 1.2) {
            return true;
        }
        else {
            return false;
        }
    }
}
