// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc166.Robot166.subsystems;

import org.usfirst.frc166.Robot166.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc166.Robot166.Robot;

/**
 *
 */
public class Vision extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    NetworkTable visionDataTable = NetworkTable.getTable("visionDataTable");

    boolean isHot;
    double timeHot;
    boolean determinedHotness = false;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initHotValues() {
        isHot = false;
        determinedHotness = false;
        timeHot = 0.0;
        SmartDashboard.putNumber("timeHot", 0.0);

    }

    public void checkIsHot() {
        if ((determinedHotness == false) && (visionDataTable.getBoolean("isHot") == true)) {
            isHot = true;
            timeHot = (Robot.timing.getCurrentAutonomousTime());
            determinedHotness = true;
            SmartDashboard.putNumber("timeHot", timeHot);
        }
    }

    public double getTimeHot() {
        return timeHot;
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new PerformVisionAction());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
